/*
 * Shared flows and flow hooks API
 *
 * Manage shared flows and flow hooks. For more information, see: * <a href=\"https://docs.gravitee.com/api-platform/fundamentals/shared-flows\">Reusable shared flows</a> * <a href=\"https://docs.gravitee.com/api-platform/fundamentals/flow-hooks\">Attaching a shared flow using a flow hook</a>.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type GraviteeLicence struct {
	//The tier gravitee is running on.
	Tier string
	//The packs included in the tier gravitee is running on.
	Packs []string
	//The features included in the tier gravitee is running on.
	Features []string
}
